//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ditto.DataCheck.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ditto.DataCheck.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executing Ditto data check process..
        /// </summary>
        internal static string BatchWelcomeMessage {
            get {
                return ResourceManager.GetString("BatchWelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation requested, please wait..
        /// </summary>
        internal static string CancellationRequestedMessage {
            get {
                return ResourceManager.GetString("CancellationRequestedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check failed.
        /// </summary>
        internal static string CheckFailedMessage {
            get {
                return ResourceManager.GetString("CheckFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data check errors: {0}.
        /// </summary>
        internal static string CheckFailuresMessageFormat {
            get {
                return ResourceManager.GetString("CheckFailuresMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check passed.
        /// </summary>
        internal static string CheckPassedMessage {
            get {
                return ResourceManager.GetString("CheckPassedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {3}:&apos;{0}&apos; {1} ({2}).
        /// </summary>
        internal static string ConsoleCheckFinishedMessageFormat {
            get {
                return ResourceManager.GetString("ConsoleCheckFinishedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanding script entity &apos;{0}.{1}&apos; matching &apos;{2}&apos; to &apos;{3}&apos;..
        /// </summary>
        internal static string ExpandingElementEventMessage {
            get {
                return ResourceManager.GetString("ExpandingElementEventMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##teamcity[buildStatisticValue key=&apos;{0}&apos; value=&apos;{1}&apos;].
        /// </summary>
        internal static string TeamCityBuildStatisticValueMessageFormat {
            get {
                return ResourceManager.GetString("TeamCityBuildStatisticValueMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##teamcity[testFailed type=&apos;{0}&apos; name=&apos;{1}&apos; message=&apos;{2}&apos; details=&apos;{3}&apos; expected=&apos;{4}&apos; actual=&apos;{5}&apos; flowid=&apos;{6}&apos;].
        /// </summary>
        internal static string TeamCityTestFailedMessageFormat {
            get {
                return ResourceManager.GetString("TeamCityTestFailedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##teamcity[testFinished name=&apos;{0}&apos; duration=&apos;{1}&apos; flowid=&apos;{2}&apos;].
        /// </summary>
        internal static string TeamCityTestFinishedMessageFormat {
            get {
                return ResourceManager.GetString("TeamCityTestFinishedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##teamcity[testStarted name=&apos;{0}&apos; flowid=&apos;{1}&apos;].
        /// </summary>
        internal static string TeamCityTestStartedMessageFormat {
            get {
                return ResourceManager.GetString("TeamCityTestStartedMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total execution time: {0}.
        /// </summary>
        internal static string TotalExecutionTimeMessageFormat {
            get {
                return ResourceManager.GetString("TotalExecutionTimeMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown check type &apos;{0}&apos;.
        /// </summary>
        internal static string UnknownCheckEventMessage {
            get {
                return ResourceManager.GetString("UnknownCheckEventMessage", resourceCulture);
            }
        }
    }
}
